services:
  nginx:
    depends_on:
      - php
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
  php:
    build: ./
    ports:
      - 9000:9000
    volumes:
      - ./html:/var/www/html
